<a href="https://colab.research.google.com/github/dlee150git/FEIR_scripts/blob/main/2024_0221.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x = np.ones((3,3))
x = np.pad(x, pad_width =1)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x[6] = 11
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [ ]:
example_tuple = ('hello',[1, 2,3])

In [ ]:
example_tuple

('hello', [1, 2, 3])

In [ ]:
type(example_tuple)

tuple

In [ ]:
x = np.zeros((3,3))
x = np.pad(x, pad_width = 1,constant_value, 1)
x

SyntaxError: positional argument follows keyword argument (<ipython-input-13-323b654084c5>, line 2)

In [ ]:
a = np.ones(25)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = a.reshape(5,5)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.zeros((8,8))
a[1::2,::2] = 1

a[::2,1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_list
type(my_list)

list

In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
my_tuple = ([8,4,6],[1, 2, 3])
my_tuple

([8, 4, 6], [1, 2, 3])

In [ ]:
np.array(my_tuple)

array([[8, 4, 6],
       [1, 2, 3]])

In [ ]:
example_tuple

('hello', [1, 2, 3])

In [ ]:
example_tuple(1)

TypeError: 'tuple' object is not callable

In [ ]:
example_tuple[1]

[1, 2, 3]

In [ ]:
example_tuple[0]

'hello'

In [ ]:
a = np.array([2,6,1,9,10,3,27])
out = a[(a>=5) & (a<=10)]
out

array([ 6,  9, 10])

In [ ]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b = np.repeat(1,10).reshape(2,-1)

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(1,4)*10
a

array([10, 20, 30])

In [ ]:
b = np.arange(3,10)*10

In [ ]:
b

array([30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.hstack((a,b))

array([10, 20, 30, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.80524811, 0.18717727, 0.29938522],
       [0.51227662, 0.28276986, 0.234361  ],
       [0.62287205, 0.06790752, 0.66607413],
       [0.55529156, 0.09092034, 0.99151278],
       [0.51178772, 0.57554881, 0.85956458]])

In [ ]:
np.set_printoptions(precision = 3)

In [ ]:
rand_arr

array([[0.805, 0.187, 0.299],
       [0.512, 0.283, 0.234],
       [0.623, 0.068, 0.666],
       [0.555, 0.091, 0.992],
       [0.512, 0.576, 0.86 ]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idx = arr % 2
out = np.where(arr % 2 == 1,-1, arr)

In [ ]:
out = arr.copy()
out[out%2 == 1] = -1
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
a = np.empty((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
def maxx(x,y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
a = np.array([2,6,1,9,10,3,27])
idx = np.where((a>=5) & (a<=10))
a[idx]

array([ 6,  9, 10])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

c = np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(1,4)*10
display(a)
b = np.append(a,np.arange(4,10)*10)
b

array([10, 20, 30])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
out = np.where(arr % 2 == 1, -1, arr)

In [ ]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.arange(9).reshape(3,3)
display(arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[::-1,:]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
original_array = np.array([1+0.j, 0.7071+0.907j])
original_array.real
# original_array.imag


array([1.   , 0.707])

In [ ]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [ ]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)


array([2, 4])

In [ ]:
def maxx(x,y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
array = np.array([1,2,3], dtype = np.int64)
array


array([1, 2, 3])

In [ ]:
size = array.size
size

3

In [ ]:
element_length = array.itemsize
element_length

8

In [ ]:
total_bytes = array.nbytes
total_bytes

24

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
idx = np.where(a==b)
idx

(array([1, 3, 5, 7]),)

In [ ]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
a =  np.array([0,10,20,40,60])
b = np.array([0, 40])
out = np.in1d(a,b)
out

array([ True, False, False,  True, False])

In [ ]:
array = np.array([1,2,3], dtype = np.int64)
size = array.size
element_size = array.itemsize
total_size = array.nbytes

In [ ]:
a = np.arange(1,4)
print(a)

[1 2 3]


In [ ]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
arr = np.arange(10)
out = arr[arr%2 == 1]
out

array([1, 3, 5, 7, 9])

In [ ]:
a = np.full((3,3), True, dtype = bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a = np.array([10, 10, 20, 20, 30, 30])
b = np.array([[1, 1], [2, 3]])

display(b)
out = np.unique(b)
out

array([[1, 1],
       [2, 3]])

array([1, 2, 3])

In [ ]:
out = np.unique(b)
out

array([10, 20, 30])

In [ ]:
out

array([10, 20, 30])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
a = np.array([0, 10, 20, 40, 60])
b = np.array([0, 40])

out = np.in1d(a,b)
out

array([ True, False, False,  True, False])

In [ ]:
a = np.random.random(15)
a

array([0.253, 0.569, 0.209, 0.352, 0.162, 0.216, 0.56 , 0.721, 0.397,
       0.951, 0.132, 0.962, 0.957, 0.469, 0.079])

In [ ]:
(a.reshape(5,3)+1)*5

array([[6.265, 7.845, 6.043],
       [6.762, 5.81 , 6.079],
       [7.8  , 8.605, 6.986],
       [9.755, 5.66 , 9.81 ],
       [9.785, 7.346, 5.396]])

In [ ]:
np.random.uniform(5,10,(5,3))

array([[5.603, 8.524, 7.782],
       [9.369, 8.182, 9.428],
       [8.751, 8.773, 6.519],
       [9.307, 9.705, 7.669],
       [6.646, 6.328, 8.599]])

In [ ]:
array = np.array([1,2,3], dtype = np.int64)

size = array.size
display(size)
element_size = array.elementsize
total_bytes = array.nbytes

3

AttributeError: 'numpy.ndarray' object has no attribute 'elementsize'

In [ ]:
arr = np.arange(1,4);
a = np.repeat(arr,3)
b = np.tile(arr,3)
out = np.hstack((a,b ))
out

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.full((3,3), True)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])